rethinkdb/docs

5-deploying-rethinkdb/paas.md
@mglukhovsky - see if this is a little clearer on how to set up VPC security groups. Part of it was already in our AWS documentation, but captioned "Cluster administration," which I don't think was really accurate.
=> Clarify secure cluster info (#548)

1-get-started/install/osx.md
The package for this release is named `rethinkdb-1.15.3-1.dmg` instead of `rethinkdb-1.15.3.dmg`. `rethinkdb-latest.dmg` always points to the latest release.
=> Use rethinkdb-latest instead of version-qualified link

2-query-language/from-sql.md
Changed the RQL queries to exclude an incorrect additional closing bracket. (two instances)
FROM:
r.table("users").filter(
r.row['name'].match("er$")}
)
TO:
r.table("users").filter(
r.row['name'].match("er$")
)
=> [DOC] Remove extra bracket from RQL queries

2-query-language/sql-to-reql/javascript.md, 2-query-language/sql-to-reql/python.md, 2-query-language/sql-to-reql/ruby.md
These changes remove the links to API documentation, making the preformatted blocks a lot simpler, and remove some redundancies in the examples.
Pinging @mglukhovsky for review.
=> Streamline SQL-to-ReQL cheat sheets

2-query-language/geo-support/javascript.md, 2-query-language/geo-support/python.md, 2-query-language/geo-support/ruby.md
"create a line object" -> "create a polygon object"
=> Fix typo in polygon command description

1-get-started/guide/python.md
Changes print from a statement to a function, which lets users on
Python 3 copy-paste the parts of the guide intended for execution
on their local machines without needing to edit the lines.
This should not affect any other versions and will run just as well
in Python 2.
=> Make examples in Python guide be Python 3 compatible

1-get-started/drivers/writing-drivers.md
Reading the docs it wasn't totally clear that tokens need to be unique per connection. It was implied from the aside about the official drivers implementation, but I think it would be good to make this explicit.
I'm not totally happy with the way I've worded this, I'd welcome any feedback or thoughts on ways to make this less awkward.
=> Clarify token uniqueness properties

4-rethinkdb-in-practice/cookbook/python.md
The final example in the [dynamic keys section of the Python cookbook](http://rethinkdb.com/docs/cookbook/python/#using-dynamic-keys-in-reql-commands) contained an unclosed code fence.
Before:
After:
It's a small fix, but I hope it helps!
=> Fix unclosed code fence

1-get-started/guide/python.md
Changing URL to match that of URL provided in the list of example projects :snake: Python projects. Also, the old URL was pointing to a page that wasn't using the new CSS properly [viewable here and is live](http://rethinkdb.com/docs/examples/flask-backbone-todo/).
=> Changing URL to match that of URL provided in the list of example projects. 

1-get-started/drivers/index.md
The current rethinkdb driver listed on the website is unsupported. The one linked is supported and up to date.
=> Updating to supported RethinkDB Adapter

api/javascript/geospatial/to_geojson.md, api/javascript/index.md, api/python/geospatial/to_geojson.md, api/python/index.md, api/ruby/geospatial/to_geojson.md, api/ruby/index.md
`table(geo)` should be `table('geo')`
=> Fix syntax error missing quote around string

1-get-started/drivers/writing-drivers.md
Reading this section it wasn't explicitly made clear that rethinkdb can return either a single SUCCESS_SEQUENCE, or multiple SUCCESS_PARTIAL's followed by a SUCCESS_SEQUENCE. This PR updates the docs to make this clearer.
Prompted by rethinkdb/rethinkdb#4616
=> Clarify how to handle streams as cursors

api/javascript/manipulating-tables/changes.md
I'm not 100% sure if this is right or not, opening a PR for discussion. With the protocol changes in v0_4, I don't think we need to run change feeds on separate connections.
If that's correct I can update the other platform docs too.
=> Don't run change feeds on separate connection

api/ruby/aggregation/max.md
The ruby doc for max forgot closing code block with ```
=> Fix missing close ``` for code block

_jekyll/_includes/debian-based-install-from-source.md
m4 wasn't in my clean install of Ubuntu 15 server, causing `sudo make install` to fail.  `sudo apt-get install m4` fixed, the problem, so I assume nothing else is pulling it in and bringing it in with the other build dependencies will fix the problem.
=> Add m4 to dependency install list

api/javascript/writing-data/update.md
The code example didn't match its description. The post with id 1 was not being selected before the update
=> fix code example

0-getting-started/install/raspbian.md
As suggested by @mogren https://github.com/rethinkdb/rethinkdb/issues/4541#issuecomment-138243806
=> ALLOW_WARNINGS=1 for Raspbian build instructions

0-getting-started/install/arch.md
Arch Build instructions regarding tricking the system into choosing right version of Python interpreter unfortunately did not work for me. Here is a correct version, which I tested, taken from Arch Wiki at https://wiki.archlinux.org/index.php/Python#Dealing_with_version_problem_in_build_scripts.
=> Fix Arch Linux build instructions

5-deployment/paas.md
Our AWS listing was moved to a new URL:
https://aws.amazon.com/marketplace/pp/B013R60Q8Y
instead of
https://aws.amazon.com/marketplace/pp/B00E9EZ5DK
The old URL is going to be removed soon, and is outdated.
@chipotle Can you merge & deploy this please when you have a moment?
=> Update AWS marketplace listing

5-deployment/paas.md
Docs was referencing old AWS EC2 instance types
=> Update AWS instance types

api/javascript/index.md
After making these changes, all examples in api/javascript/index.md
compile properly.
=> Fix syntax errors in JavaScript API doc examples

0-getting-started/build.md, 0-getting-started/install/arch.md, 0-getting-started/install/centos.md, 0-getting-started/install/debian.md, 0-getting-started/install/fedora.md, 0-getting-started/install/index.md, 0-getting-started/install/mint.md, 0-getting-started/install/opensuse.md, 0-getting-started/install/osx.md, 0-getting-started/install/raspbian.md, 0-getting-started/install/ubuntu.md, _jekyll/_includes/debian-based-install-from-source.md
download.rethinkdb.com now supports https. I switched some of the links over (most importantly the ones where we download a gpg key for the debian/ubuntu packages).
=> Changed some download links to https

2-data-model/data-modeling-in-rethinkdb.md
I think we can be a bit more clear in the fact that if a modification is made to a document, the entire document has to be rewritten to disk instead of being able to update just that single field to disk. 
This is important when considering multi-megabyte embedded documents and having to wait for that write to occur. 
@chipotle @danielmewes do you concur?
=> Clarity in data modeling documentation

api/javascript/manipulating-tables/table_create.md, api/python/manipulating-tables/table_create.md, api/ruby/manipulating-tables/table_create.md
All three versions of the API docs state that trying to create a table
with a name that duplicates an existing table will raise a
ReqlRuntimeError. This contradicts the test at lines 132-136 of
test/rql_test/src/meta/table.yaml which specifies that in this case a
ReqlOpFailedError should be raised.
Docs have been updated to match behavior specified by test.
=> Fixed inconsistency in table_create api docs

api/javascript/index.md, api/javascript/joins/zip.md, api/python/index.md, api/ruby/index.md, api/ruby/joins/zip.md
A few examples had the wrong/missing language specifications in the JS docs.
The same examples seem to be fine for the other languages.
@chipotle Could you review please?
=> Fixed wrong code block style in JS docs

0-getting-started/drivers/java.md, 1-reql-language/guide/java.md
The instructions for Using gradle is missing a 'group' key.
=> Add missing "group" for Gradle, Fix compile errors and a typo on row.g("name").

2-data-model/data-modeling-in-rethinkdb.md
Little change to keep the Python API consistent on the doc. It just changes `getAll` to `get_all`
Thanks! (I've signed the [cla](http://rethinkdb.com/community/cla/) just in case)
=> Keep Python API throughout the data modeling docs

api/python/aggregation/ungroup.md
Makes the formatting of the examples nice again.
=> Removes unnecessary backticks in python/ungroup.md

0-getting-started/install/windows.md
Was trying RehtinkDB on Windows, noticed issue #1025, resolves small `-j` parameter sign error.
Fixes #1025
=> Fixes a small parameter error on "Install RethinkDB on Windows" Resolves #1025

api/java/aggregation/ungroup.md, api/javascript/aggregation/ungroup.md, api/python/aggregation/ungroup.md, api/ruby/aggregation/ungroup.md
Added an example for `ungroup`. It might be a little out-of-place, but it demonstrates using `ungroup` along with a large number of rethink keywords.
Also cleans up formatting errors in the [upgroup java page](http://rethinkdb.com/api/java/ungroup/).
=> Additional examples for ungroup

api/python/joins/eq_join.md
I've signed the [cla](http://rethinkdb.com/community/cla/) just in case
Also, making this change, I have noticed that one of the examples (using secondary indexes) is:
`r.table('arenas').eqJoin('cityId', r.table('arenas'), {index: 'cityId'}).run(conn, callback)`
Shouldn't it read:
`r.table('players').eqJoin('cityId', r.table('arenas'), {index: 'cityId'}).run(conn, callback)`
?
=> Rewrite CamelCase keys to underscore on the Python `eqJoin` docs

7-developing/frameworks-and-libraries.md
Our driver has been supporting promises natively for a while, so I think this tool isn't necessary anymore.
=> Remove rql-promise from integrations tool list.

3-reql-practice/cookbook/ruby.md
Added missing back ticks here.
https://rethinkdb.com/docs/cookbook/ruby/
=> Adds missing back ticks for code blocks in cookbook ruby docs

0-getting-started/install/raspbian.md
I was following the installation instructions on a brand new Raspbian and got stuck with this error:
```fatal error: openssl/sha.h: No such file or directory```
Turns out, I just had to install another dependency:
```sudo apt-get install libssl-dev```
OT: I was able to successfully install rethinkdb after that. The compilation process took **several** hours on the latest Raspberry PI 3 model, I don't know if this is something we should mention in the docs.
=> add libssl-dev to list of dependencies

0-getting-started/install/osx.md
Building on OS X usually requires this flag now.
=> Add `--fetch openssl` to OS X build instructions

5-deployment/config-file.md
Fix for the documentation side of https://github.com/rethinkdb/rethinkdb/issues/5853
=> Mention host:post format for canonical-address

7-developing/writing-drivers.md
The current indentation on function serialization makes it look as if `[ADD ...]` belongs to `MAKE_ARRAY` as opposed to belonging to `FUNC`. This change de-indents it by one space to make it clearer.
=> Clearer indentation on function serialization

api/python/transformations/slice.md, api/ruby/transformations/slice.md
This fixes 6ba42741395b19c68f8007edefbaebc048b0e5e2 which broke api/python/transformations/slice.md and api/ruby/transformations/slice.md.
=> Fix slice.md broken by merge

api/javascript/administration/grant.md, api/javascript/aggregation/ungroup.md, api/javascript/control-structures/branch.md, api/javascript/selecting-data/between.md, api/javascript/writing-data/update.md
This commit standardises the JavaScript code examples to make them
easier to parse using automated tools.
=> Standardise JavaScript code examples

api/javascript/selecting-data/get_all.md
Use getAll instead of get_all as per the rest of the javascript documentation
=> Use camelCase for get_all / getAll

1-reql-language/nested-fields/java.md, 1-reql-language/nested-fields/javascript.md, 1-reql-language/nested-fields/python.md, 1-reql-language/nested-fields/ruby.md
The "Accessing nested fields" docs seemed to have some (minor) typos that caused the examples to not make sense. Additionally, removing the arrays from some of the pluck commands also seems to better match ES6's destructuring syntax. Have only tested, and so updated, the JS examples but if the other language examples should match I can add another commit.
Thanks rethinkdb team, cool product!
=> Fix typos in "Accessing nested fields"

8-architecture/comparison-tables.md
Updated MongoDB concurrency information in comparison-tables. v2.2.0 release is from 2012-08. That's outdated and misleading.
=> update outdated data for mongodb concurrency

0-getting-started/drivers/python.md, 1-reql-language/asynchronous.md, 1-reql-language/guide/python.md, 1-reql-language/introduction-to-reql.md, 3-reql-practice/tutorials/superheroes.md, 4-admin/administration-tools.md, 7-developing/rabbitmq/python.md, api/python/accessing-rql/r.md, api/python/index.md
Latest RethinkDB python drivers >=2.4.0 are **no longer** using `import rethinkdb as r`.
instead it uses: `from rethinkdb import RethinkDB`
then: `r = RethinkDB()`
=> use RethinkDB python driver >=2.4.0 import method

api/java/transformations/union.md, api/javascript/transformations/union.md, api/python/transformations/union.md, api/ruby/transformations/union.md
Closes #1231 
Corrects documentation for `union` `interleave` argument, which uses the return value to sort rows. The documentation currently incorrectly states that the return value should be _"a string to take as a field name"_.
See the [rethinkdb tests](https://github.com/rethinkdb/rethinkdb/blob/98fd78409095a25b04dcaf0eadd6719f381a7d7e/test/rql_test/src/transform/unordered_map.yaml#L34) for examples of this in action.
=> union: fix misleading description of interleave when a function

api/java/control-structures/uuid.md, api/javascript/control-structures/uuid.md, api/python/control-structures/uuid.md, api/ruby/control-structures/uuid.md
Version 5 UUIDs can’t be considered guaranteed unique if they’re computing based on user data, because they use SHA-1. This should be mentioned in the docs.
=> Add notification about version 5 UUID

3-reql-practice/cookbook/index.md
The links to the language-specific cookbooks on the cookbook index page are broken. The PR fixes them.
=> Fix links on cookbook index page

api/java/manipulating-tables/index_wait.md, api/javascript/manipulating-tables/index_wait.md
Removes blank line after YAML.  The docs were properly generated
for Python and Ruby, but not Java and JavaScript.
=> Try fixing related_commands parsing in index_wait.md

api/java/math-and-logic/bit_not.md, api/javascript/math-and-logic/bit_not.md, api/python/math-and-logic/bit_not.md, api/ruby/math-and-logic/bit_not.md
- [x ] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/
correct results for bit_not examples
=> correct result for bit_not examples

api/java/index.md
Fixes #1190:
> From [rethinkdb/rethinkdb#6211](https://github.com/rethinkdb/rethinkdb/issues/6211):
> 
> > On https://rethinkdb.com/api/java/#connect, it says that `r.connection().timeout()` is the timeout in seconds. It should say milliseconds.
=> Fixes documentation for timeout

api/java/selecting-data/get.md
There is an excessive underscore in front of the third 'Example' on [the page of the `get` command](https://rethinkdb.com/api/java/get).
Nothing fancy, I just removed the excessive underscore.
**Checklist**
=> Minor change (removed excessive underscore)

api/java/dates-and-times/time.md
As described in issue #1291 using single quotes leads to an exception.
Simply fixed the documentation of the `time` commands `timezone` argument to `String` type.
**Checklist**
=> Fixed documentation as described in issue #1291

api/java/control-structures/default.md
The documentation for the java driver mentions `default` at the top of the page (i.e. `value.default(default_value) -> any`) while the method itself is called `default_` due to java having a primitive called default.
This PR modifies the java doc by actually showing the right method to prevent possible confusion.
**Code examples**
**Checklist**
**References**
Changes made apply to the following docs
https://rethinkdb.com/api/java/default/
=> Use actual method name

0-getting-started/drivers/java.md
Update Java Driver versions in the docs
bumped version used from 2.3.3 -> 2.4.4 in `0-getting-started\drivers\java.md`
**Code examples**
N/A
**Checklist**
- [✔] I have read and agreed to the [RethinkDB Contributor License Agreement](http://rethinkdb.com/community/cla/)
**References**
Nope
=> Update Java Driver Versions

5-deployment/config-file.md
https://github.com/rethinkdb/rethinkdb/issues/7061#issuecomment-1119596216
Added a section to the config file doc describing the `initial-password` option.
**Checklist**
=> Describe `initial-password` config file option

api/java/manipulating-databases/db_create.md, api/javascript/manipulating-databases/db_create.md, api/python/manipulating-databases/db_create.md, api/ruby/manipulating-databases/db_create.md
It seems the docs are out of date, that hyphens are allowed in database names (https://github.com/rethinkdb/rethinkdb-python/pull/183).
I updated a single sentence in the JavaScript, Python, Ruby and Java docs. (should be clear from the commit)
I updated the sentence to have word order similar to the Web UI error notice given when creating a database with an invalid name, `You can only use alphanumeric characters, hyphens and underscores for a database's name.`.
**Code examples**
NA
**Checklist**
**References**
NA
=> Add that hyphens are valid in database names

0-getting-started/install/index.md
The s390x architecture is supported by RethinkDB, but it is missing from the docs.
This PR adds s390x support and recognizes the help of the `Open Source Software Developer Cloud on LinuxONE`'s support with the build machine.
**Checklist**
**References**
- https://github.com/rethinkdb/rethinkdb/issues/7071
=> docs: add s390x

1-reql-language/guide/index.md
See https://github.com/rethinkdb/docs/issues/1345
The page /docs/guide was being accessed, but the links were
relative to /docs/guide/ with the trailing slash.
=> Use absolute paths.

0-getting-started/install/index.md, 0-getting-started/install/windows.md
Uncomments the Windows link and makes the page hard-code 2.4.3.
Since the page hardcodes 2.4.3, we'll want to undo that once 2.4.3 is released.
=> Update for early Windows 2.4.3 release

0-getting-started/drivers/index.md
It is useful to have an alternative in driver selection if there is one available
Link to the [Rust driver](https://github.com/vettich/un-rethinkdb-rs) from https://rethinkdb.com/docs/install-drivers
=> Add yet another Rust driver
