api/javascript/manipulating-tables/changes.md
=> relative link didn't work

api/ruby/manipulating-tables/changes.md
=> Change `None` into `nil` in Ruby doc of changes()

4-rethinkdb-in-practice/frameworks-and-libraries.md
Proposing to add express-session-rethinkdb to the list of nodejs drivers and extensions list.
=> Added express-session-rethinkdb

api/python/selecting-data/filter.md
=> Fix invalid syntax

4-rethinkdb-in-practice/frameworks-and-libraries.md
phpReAdmin os an php web frontend to RethinkDB
=> add phpReAdmin with corrections by Daniel Mewes

api/javascript/document-manipulation/difference.md
Make first example a little more clearer by spreading over multiple lines
=> Add an update example to difference

4-rethinkdb-in-practice/cookbook/index.md
=> Fix typo on cookbook index page

1-get-started/guide/javascript.md, 1-get-started/guide/python.md, 1-get-started/guide/ruby.md, 4-rethinkdb-in-practice/publish-subscribe/javascript.md, 4-rethinkdb-in-practice/publish-subscribe/python.md, 4-rethinkdb-in-practice/publish-subscribe/ruby.md
Contributor's agreement previously signed.
=> Copy edits for typos

3-learn-the-tools/sharding-and-replication.md
I have signed the CLA  :sparkles:
=> Fix formatting error on Sharding and replication

1-get-started/drivers/index.md
Add an Erlang driver that supports JSON protocol, changefeed and anonoymous filter (WIP).
I signed CLA before.
=> Add Erlang driver

index.html
=> Fix critical typo in docs: geting -> getting

8-architecture/faq.md
Added an faq entry on feeds scalability since people ask us all the time.
/cc @mglukhovsky @chipotle, please review.
=> Feeds scalability faq

0-getting-started/drivers/java.md
For those Java (or Scala) developers who build using SBT (Simple Build Tool)
=> Add "Using SBT" instructions

0-getting-started/drivers/java.md
pom.xml example is missing the dependency tag.
Also added missing Connection type.
=> Missing dependency tag in pom.xml example.

1-reql-language/changefeeds/python.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/rethinkdb/docs/990)
=> Add line to fix code highlighting.

1-reql-language/external-api-access.md
=> Adds nonAtomic to the update command in r.http doc. Resolves #1030

1-reql-language/guide/java.md, 1-reql-language/guide/javascript.md, 1-reql-language/guide/python.md, 1-reql-language/guide/ruby.md, api/java/control-structures/type_of.md, api/javascript/control-structures/type_of.md, api/python/control-structures/type_of.md, api/ruby/control-structures/type_of.md
Just reading through the docs and stumbled upon a couple of broken links.
=> fix broken (relative) urls

api/java/index.md, api/java/manipulating-tables/table_drop.md, api/ruby/dates-and-times/year.md, api/ruby/index.md
Came across minor missing formatting and have signed the CLA.
=> Adds minor missing backticks in ruby and java API

_jekyll/_data/api_javascript.yml, api/javascript/document-manipulation/object.md, api/javascript/index.md
=> Fixed the typo error of coerce_to to coerceTo in javascript docs issue#1092

api/python/index.md, api/python/math-and-logic/mod.md
Now, I made change in  api/python/math-and-logic/mod.md too
=> Typo removed

0-getting-started/install/windows.md
We're dropping the "beta" tag from the Windows port with the next update (coming up next week).
@coffeemug and @chipotle do these formulations sound good to you?
=> Prepare for fully supported Windows release

0-getting-started/drivers/java.md
Our latest available driver version is 2.3.3.
@chipotle
=> Updated Java driver versions

1-reql-language/map-reduce-in-rethinkdb.md
=> Fix typo and grammar in GMR example explanation

4-admin/sharding-and-replication.md
Fix syntax errors in sharding and replication docs
=> Fix syntax errors in sharding and replication docs

api/ruby/aggregation/min.md
There is a missing code block closure here https://www.rethinkdb.com/api/ruby/min/. See the screenshot below:
=> Add missing code block close

0-getting-started/install/debian.md, 0-getting-started/install/mint.md, 0-getting-started/install/ubuntu.md
Hi,
There were some extra quotation marks at the end of the commands that make shell to expect some more inputs. Now they are gone and everything is fine.
Thanks in advance!
=> fix: update docs

8-architecture/faq.md
Updates FAQ to reflect new license.
=> Update FAQ for APL relicensing

4-admin/third-party-admin-tools.md
=> add reqlpro to thrid party tools

api/ruby/control-structures/branch.md
Fix Ruby code example by replacing comma.
=> Fix syntax in ruby api doc

3-reql-practice/examples.md
I've pieced together a working boilerplate for changefeed interaction demonstration with a Redux store.
[boilerplate](https://github.com/ddaaggeett/webstarter-with-database) documentation will be included over time - however, it's fairly simple to follow how Redux is alternatively triggered by RethinkDB changefeeds as opposed to immediately triggering redux action creators. User actions in this case trigger a RethinkDB query which in-turn send changefeeds to trigger redux action creators.
=> added example: changefeed sync with redux app state boilerplate

_jekyll/_standalone/assets/css/styles.css
=> Change text color from #647276 to black

4-admin/system-jobs.md
=> Add "query" and "user" fields to system.jobs queries

0-getting-started/install/centos.md, 0-getting-started/install/debian.md, 0-getting-started/install/fedora.md, 0-getting-started/install/mint.md, 0-getting-started/install/ubuntu.md, 4-admin/migration.md
Adds instructions for use of the CentOS 8 yum repo.
=> Basic CentOS 8 instructions

api/javascript/transformations/sample.md
=> Stratification sample

api/javascript/writing-data/delete.md
Just a small grammar fix, if I find anymore problems, I will fix those too :smile:
=> made a small grammar fix

0-getting-started/install/raspbian.md
Update the Raspbian install instructions based on https://github.com/rethinkdb/rethinkdb/issues/6785.
=> Adjust raspbian install instructions

_jekyll/_standalone/_layouts/api-command.html
Change relative URL handling of related commands. Fixing issue https://github.com/rethinkdb/docs/issues/1251
=> Change relative url handiling of related commands

1-reql-language/external-api-access.md, 4-admin/permissions-and-accounts.md, 5-deployment/security.md, 9-security/vulnerablilites.md, api/javascript/control-structures/http.md, api/javascript/index.md, api/python/control-structures/http.md, api/python/index.md, api/ruby/control-structures/http.md, api/ruby/index.md
Add notification that the Admin UI can be exploited when it is not behind a proxy and letting `r.http` handle user provided content.
=> r.http and admin ui proxy notifications

9-security/vulnerablilites.md
Replace my email address with a rethinkdb email address.
=> Replace email address

9-security/mobile-connections.md, _jekyll/_data/docs-nav.yml
I've written a security article due to attempt from users to connect to a RethinkDB server via Android, and the implications of doing such thing.
=> Article: Security issues regarding mobile connections

_jekyll/_data/api_java.yml, api/java/selecting-data/pathspec.md
Documents a feature recently added to the Java driver called `pathspec`.
=> Documentation for Java's pathspec

0-getting-started/install/arch.md
=> Update Arch Linux build instructions

api/javascript/aggregation/count.md
Work also on array type
Better doc for count(), missing array info.
=> Complete doc

0-getting-started/build.md, 0-getting-started/install/arch.md, 0-getting-started/install/centos.md, 0-getting-started/install/debian.md, 0-getting-started/install/fedora.md, 0-getting-started/install/index.md, 0-getting-started/install/mint.md, 0-getting-started/install/opensuse.md, 0-getting-started/install/osx.md, 0-getting-started/install/raspbian.md, 0-getting-started/install/ubuntu.md, 0-getting-started/install/windows.md, _jekyll/_includes/debian-based-install-from-source.md
https://rethinkdb.com/blog/download-server-changes
=> Replace download server links and have a statement about windows

0-getting-started/drivers/python.md
Minor typo spelling correction in docs
**Checklist**
=> Typo in python.md doc

8-architecture/faq.md
See https://github.com/rethinkdb/rethinkdb/issues/6930
**Checklist**
=> Remove Mediafly mention from FAQ

0-getting-started/drivers/ruby.md
I found some old notation in the sample code and fixed it.
=> Modernize sample code

README.md
A word in README was duplicated.
Removed excessive word.
**Checklist**
=> Minor change (removed duplicate word)

0-getting-started/install/ubuntu.md
=> Update ubuntu instructions for apt-key deprecation

0-getting-started/install/ubuntu.md
=> Fixup for Ubuntu instructions

0-getting-started/install/index.md, 0-getting-started/install/ubuntu.md
=> Install instruction fixups

4-admin/migration.md
Addressing #1341.
**Checklist**
=> Add more migration instructions

0-getting-started/install/index.md
=> Add more information about architectures

1-reql-language/guide/java.md
=> Fix broken image URL in /docs/guide/java/

api/java/manipulating-tables/set_write_hook.md, api/javascript/manipulating-tables/set_write_hook.md, api/python/manipulating-tables/set_write_hook.md, api/ruby/manipulating-tables/set_write_hook.md
The docs were wrong.
**Checklist**
=> Fix documentation for set_write_hook result
